name: buildx

on:
  schedule:
    - cron: "37 08 * * *"
  pull_request:
  push:

jobs:
  buildx:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker Buildx (build)
        uses: docker/build-push-action@v2.5.0
        if: success() && !contains(github.ref, 'master')
        with:
          push: false
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          platforms: linux/amd64
          tags: timbru31/alpine-java-maven:latest

      - name: Docker Login
        if: success() && contains(github.ref, 'master')
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        uses: docker/build-push-action@v2.5.0
        if: success() && contains(github.ref, 'master')
        with:
          push: true
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          platforms: linux/amd64
          tags: timbru31/alpine-java-maven:latest

      - name: Inspect Image
        if: always() && github.event_name != 'pull_request' && contains(github.ref, 'master')
        run: |
          docker buildx imagetools inspect timbru31/alpine-java-maven:latest

      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json
